In [162]:
import numpy as np


In [163]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [164]:
array.min(), array.max(), min(array), max(array)

(np.int64(10), np.int64(500), np.int64(10), np.int64(500))

In [165]:
array.sum(), sum(array)

(np.int64(1338), np.int64(1338))

In [166]:
array.mean()

np.float64(111.5)

In [167]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array.min(), array.argmin()

(np.int64(10), np.int64(3))

In [168]:
array.max(), array.argmax()

(np.int64(500), np.int64(2))

In [169]:
l = [23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30]
l.index(30)

5

In [170]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array


array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [171]:
array[array > 100]

array([500, 310, 101, 203])

In [172]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [173]:
array[-1]

np.int64(30)

In [174]:
array[-2:]

array([203,  30])

In [175]:
array[array % 2 == 0]

array([500,  10,  40,  30, 310,  20,  30,  30])

In [176]:
array[(array % 2 == 0) & (array > 50)]

array([500, 310])

In [177]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [178]:
array[(array % 3 == 0) | (array < 40)]

array([23, 10, 30, 20, 30, 30])